### ISSUE TITLE
Login doesn't work with android: can't connect to "localhost/127.0.0.1:3000" 

### ISSUE THREAD

**Issue by asallem** [shanhuiyang/TypeScript-MERN-Starter#106]
Login doesn't work with android: can't connect to "localhost/127.0.0.1:3000" 
solution => adb reverse tcp:3000 tcp:3000

**Comment by shanhuiyang** [comment]
Hi @asallem , thanks for your reporting. Indeed this is a known issue as #56 .
As we illustrated [in the readme](https://github.com/shanhuiyang/TypeScript-MERN-Starter#start-the-mobile-apps), you need to change the HosrUrl manually to the LAN IP.

We would like to resolve this issue in near future but need time on that.
