### ISSUE TITLE
Not able to build the project (yarn start)

### ISSUE THREAD

**Issue by abhimanyu56** [shanhuiyang/TypeScript-MERN-Starter#113]
Getting this following error in many files.
Attached Screnshot.
<img width="1266" alt="Screenshot 2020-06-28 at 2 52 17 AM" src="https://user-images.githubusercontent.com/1777553/85932526-7a2f4e00-b8ea-11ea-8a5c-3d399915662a.png">

server/controllers/article.ts:89:29 - error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

89         if (Number.parseInt(req.query.rating) === 1) {
                               ~~~~~~~~~~~~~~~~

**Comment by shanhuiyang** [comment]
Thanks for feedback, will fix it in this week.

**Comment by shanhuiyang** [comment]
@abhimanyu56
Are you newly cloned repo? I cloned a new repo and did not found the issue.
I guess you met the issue while you pulled the new commits. Could you please remove the node_modules and dist/build folders then try again?

**Comment by abhimanyu56** [comment]
@shanhuiyang Its working fine now for me as well... Issue was I did npm update and not yarn.
Can you please tell me why it was not working with nom update?

**Comment by shanhuiyang** [comment]
As I know `npm update` just has some bugs. I did not know the detail defect of npm but just recommend `yarn` at the beginning. Maybe you can search around for this issue.

Thanks for the feedback anyway!
